### PR TITLE
Separate queries of stream row and events in read operation

### PR DESCRIPTION
**Pull request by OleksiiZuiev**
Currently on the read operation events & stream row are queried with a single TableQuery. This can result in a slow traversing of multiple pages to get the results.

This PR splits reading into 2 queries: query of stream row and query of events range - such queries return results without paging.

### CODE REVIEW

**Comment by yevhen** [comment]
Good one! Many thanks for PR!!

**Comment by iamim** [comment]
Could this change introduce any problems from the perspective of HEAD and events fetch not being atomic?
E.g. if fetched HEAD is ahead of events and in reverse.

**Comment by yevhen** [comment]
Nothing really changed in terms of behavior. It was never transactional (Azure doesn't guarantee consistent multi-row reads within a single query).

The returned stream header is solely for informational purposes. So occasionally you may have `stream.Version < slice.Events.Last().Version` (the reverse situation is normal since you read stream in slices). Always use the last version event when [reading](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S05_Read_from_stream.cs#L56). 

If you want the stream header to be in 100% sync with events you can either drop off excess events or re-read until `slice.Events.Last().Version == stream.Version`.

**Comment by iamim** [comment]
@yevhen wouldn't it violate optimistic concurrency promise?
Assuming we have 2 readers/writers (A and B) and a stream with 5 events (SS-HEAD.Version=5, ETag="5").
Concurrently, A reads the stream while B append Version 6:
- A receives events [1..5] first
- B appends Version=6
- A receives head with Version=6 and ETag="6"
- A folds events, checks invariants, and appends an event with Version=6, which succedes since A passes ETag="6"
- We end up with SS-HEAD.Version=7, ETag="7" and 2 events with Version=6

Am I missing something?

**Comment by yevhen** [comment]
@iamim A will get concurrency conflict on insert of event with Version=6. SS optimistic concurrency works on both stream header and events

**Comment by yevhen** [comment]
You can write a simple unit test to prove it. Or you can check some of the existing tests

**Comment by iamim** [comment]
Ah, I see now, thanks for explanation.
Does it mean that header has no responsibilities? In other words, the whole system would happily work with `Partition` passed arround instead of `Stream`?

**Comment by yevhen** [comment]
@iamim almost)) the header should match for OCC to work for stream properties stored inside stream header row and since SS allows gaps in version sequencing. That's by design.

**Pull request merged**
