### PR TITLE
Migrate from Microsoft.Azure.Cosmos.Table to Azure.Data.Tables

### LINKED ISSUE #64: Migrate from Microsoft.Azure.Cosmos.Table toAzure.Data.Tables
The [`Microsoft.Azure.Cosmos.Table`](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table) package has been deprecated in favor of [`Azure.Data.Tables`](https://www.nuget.org/packages/Azure.Data.Tables/). Consider migrating to support `Azure.Data.Tables`.

### PR DESCRIPTION
**Pull request by sergiojrdotnet**
Fixes #64

### CODE REVIEW

**Comment by sergiojrdotnet** [comment]
@yevhen could you please update the continuous integration environment to net 8?

**Comment by yevhen** [comment]
Wow! This is so cool! I would try to review and release it this week! Amazing work!

**Comment by yevhen** [comment]
@sergiojrdotnet 3.0.0 is on nuget! Thanks for the incredible effort you did to make it happen! 💪 🔝 🥇

**Comment by yevhen** [comment]
> @yevhen could you please update the continuous integration environment to net 8?

appveyor didn't refresh their build images yet and I was unlucky trying to install the .net 8 SDK into Ubuntu 20.04 using MS provided instructions( Will update once appveyor roll out the officially supported version

**Comment by sergiojrdotnet** [comment]
> > @yevhen could you please update the continuous integration environment to net 8?
> 
> appveyor didn't refresh their build images yet and I was unlucky trying to install the .net 8 SDK into Ubuntu 20.04 using MS provided instructions( Will update once appveyor roll out the officially supported version

Very nice, I'm planning to also send a performance improvement PR soon.

**Pull request merged**
