### PR TITLE
Upgrade to netstandard2.0 support

### PR DESCRIPTION
**Pull request by Soarc**
Changed projects to target to netstandard 2.0 and netstandard 1.3 frameworks.
Updated nunit to 3.0.
Updated WindowsAzure.Storage to 8.3.0 version. 
Fixed failing tests. Azure Storage Emulator 5.2 now required.

### CODE REVIEW

**Comment by yevhen** [comment]
Uhh, nice one! Does it builds locally? If yes, don't worry about AppVeyour - it probably doesn't have NETCORE20 SDK installed. I'll merge your PR to branch and then we can continue poking around with scripts and appveyour to make it work there

**Comment by yevhen** [comment]
Or we can continue working in your branch

**Comment by Soarc** [comment]
Yes, it builds locally and all tests run. 
Here are appveyor issues to track.
https://github.com/appveyor/ci/issues/1729 -netcore sdk
https://github.com/appveyor/ci/issues/1702 - Azure Storage Emulator 5.2

There are some workarounds with installing SDK and emulator manualy, but i don't know how to make them work with nake. In yaml it is done by adding following lines
+install:
 +  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
 +  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log

**Comment by yevhen** [comment]
Cool. Added to install script on AppVeyour.

**Comment by yevhen** [comment]
@Soarc fixed package script. Please accept and it should fix all

**Comment by yevhen** [comment]
Check out! https://ci.appveyor.com/project/yevhen/streamstone/build/123

**Comment by yevhen** [comment]
@Soarc ok, no worries. I'll merge and fix then. Thanks for all the hard work!! This is incredible!

**Comment by Soarc** [comment]
Nice job mate, thanks.
Can you make alpha release, so nuget package become available?

**Comment by yevhen** [comment]
Till EoD. There still some things need to be cleaned up like blocking calls of async methods. Shouldn't take much time.

**Pull request merged**
